-- Sorasaki — atualização segura para quem já executou o schema.sql
-- Execute uma vez no SQL Editor do Supabase.

create unique index if not exists uq_orders_payment_id
  on public.orders(payment_id)
  where payment_id is not null;

create unique index if not exists uq_reports_group_reporter
  on public.reports(group_id, reporter_id);

insert into public.promotion_plans (name, description, price, duration_days, active)
values
  ('IMPULSIONAR', 'Maior visibilidade durante o período contratado.', 0, 7, false),
  ('PLUS', 'Mais destaque e benefícios adicionais durante o período contratado.', 0, 15, false),
  ('VIP', 'Maior nível de exposição durante o período contratado.', 0, 30, false)
on conflict (name) do nothing;


-- ===== Sistema de perfil / conta =====
alter table public.profiles add column if not exists username text;
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

alter table public.profiles drop constraint if exists profiles_username_format;
alter table public.profiles add constraint profiles_username_format
  check (username is null or username ~ '^[A-Za-z0-9_]{3,24}$');

create unique index if not exists uq_profiles_username
  on public.profiles(lower(username))
  where username is not null;

drop policy if exists "profiles own update" on public.profiles;
create policy "profiles own update" on public.profiles
  for update to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);


-- ===== Divulgações completas e grupos oficiais =====
alter table public.groups add column if not exists tags text;
alter table public.groups add column if not exists contact_url text;
alter table public.groups add column if not exists highlight text;
alter table public.groups add column if not exists view_count bigint not null default 0;

alter table public.groups drop constraint if exists groups_tags_length;
alter table public.groups add constraint groups_tags_length check (tags is null or char_length(tags) <= 300);
alter table public.groups drop constraint if exists groups_contact_url_length;
alter table public.groups add constraint groups_contact_url_length check (contact_url is null or char_length(contact_url) <= 1000);
alter table public.groups drop constraint if exists groups_highlight_length;
alter table public.groups add constraint groups_highlight_length check (highlight is null or char_length(highlight) <= 160);
alter table public.groups drop constraint if exists groups_view_count_nonnegative;
alter table public.groups add constraint groups_view_count_nonnegative check (view_count >= 0);

create or replace function public.increment_group_view(p_group_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.groups set view_count = view_count + 1
  where id = p_group_id and status = 'approved';
end;
$$;
revoke all on function public.increment_group_view(bigint) from public;
grant execute on function public.increment_group_view(bigint) to anon, authenticated;

create table if not exists public.official_groups (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  category text not null check (category in ('vendas','comunidade','jogos','estudos','outros')),
  avatar_url text,
  invite_url text not null,
  highlight text,
  display_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (char_length(name) between 2 and 100),
  check (char_length(description) between 10 and 800),
  check (avatar_url is null or char_length(avatar_url) <= 1000),
  check (char_length(invite_url) between 10 and 1000),
  check (invite_url ~* '^https?://'),
  check (highlight is null or char_length(highlight) <= 160)
);
create index if not exists idx_official_groups_active_order on public.official_groups(active, display_order, created_at);
create or replace function public.touch_official_group_updated_at()
returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end; $$;
drop trigger if exists trg_official_groups_updated_at on public.official_groups;
create trigger trg_official_groups_updated_at before update on public.official_groups for each row execute function public.touch_official_group_updated_at();
alter table public.official_groups enable row level security;
drop policy if exists "public active official groups read" on public.official_groups;
create policy "public active official groups read" on public.official_groups for select to anon, authenticated using (active = true or public.is_admin());
drop policy if exists "admins manage official groups" on public.official_groups;
create policy "admins manage official groups" on public.official_groups for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "users own groups update" on public.groups;
create policy "users own groups update" on public.groups for update to authenticated using (auth.uid() = owner_id) with check (auth.uid() = owner_id and status = 'pending' and featured_by_admin = false and admin_badge is null);
drop policy if exists "users own groups delete" on public.groups;
create policy "users own groups delete" on public.groups for delete to authenticated using (auth.uid() = owner_id);


-- ===== Divulgações completas + grupos oficiais =====
alter table public.groups add column if not exists tags text[] not null default '{}';
alter table public.groups add column if not exists highlight_phrase text;
alter table public.groups add column if not exists contact text;
alter table public.groups add column if not exists view_count bigint not null default 0;

alter table public.groups drop constraint if exists groups_category_check;
alter table public.groups add constraint groups_category_check check (category in ('vendas','comunidade','jogos','freefire','divulgacao','amizades','suporte','estudos','outros'));
alter table public.groups add constraint groups_highlight_len check (highlight_phrase is null or char_length(highlight_phrase) <= 180);
alter table public.groups add constraint groups_contact_len check (contact is null or char_length(contact) <= 500);
alter table public.groups add constraint groups_tags_len check (cardinality(tags) <= 15);
alter table public.groups add constraint groups_view_count_nonnegative check (view_count >= 0);

create table if not exists public.official_groups (
  id bigint generated by default as identity primary key,
  name text not null, description text not null,
  category text not null check (category in ('vendas','comunidade','jogos','freefire','divulgacao','amizades','suporte','estudos','outros')),
  invite_url text not null check (invite_url ~* '^https?://'),
  image_url text, highlight_phrase text, display_order integer not null default 0,
  active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  check (char_length(name) between 2 and 100), check (char_length(description) between 10 and 800),
  check (image_url is null or char_length(image_url) <= 1000), check (highlight_phrase is null or char_length(highlight_phrase) <= 180)
);
create index if not exists idx_official_groups_active_order on public.official_groups(active, display_order, created_at desc);
alter table public.official_groups enable row level security;
drop policy if exists "public active official groups read" on public.official_groups;
create policy "public active official groups read" on public.official_groups for select to anon, authenticated using (active = true or public.is_admin());
drop policy if exists "admins manage official groups" on public.official_groups;
create policy "admins manage official groups" on public.official_groups for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "users own groups update" on public.groups;
create policy "users own groups update" on public.groups for update to authenticated using (auth.uid() = owner_id) with check (auth.uid() = owner_id);
drop policy if exists "users own groups delete" on public.groups;
create policy "users own groups delete" on public.groups for delete to authenticated using (auth.uid() = owner_id);

create or replace function public.increment_group_view(p_group_id bigint) returns void language sql security definer set search_path = public as $$ update public.groups set view_count = view_count + 1 where id = p_group_id and status = 'approved'; $$;
revoke all on function public.increment_group_view(bigint) from public;
grant execute on function public.increment_group_view(bigint) to anon, authenticated;

create or replace function public.protect_group_owner_changes() returns trigger language plpgsql security definer set search_path = public as $$
begin
 if not public.is_admin() then
   if new.owner_id <> old.owner_id or new.featured_by_admin <> old.featured_by_admin or coalesce(new.admin_badge,'') <> coalesce(old.admin_badge,'') or coalesce(new.admin_note,'') <> coalesce(old.admin_note,'') or new.approved_at is distinct from old.approved_at then raise exception 'alteração não permitida'; end if;
   if old.status <> new.status and new.status <> 'pending' then raise exception 'alteração não permitida'; end if;
 end if;
 return new;
end; $$;
drop trigger if exists trg_protect_group_owner_changes on public.groups;
create trigger trg_protect_group_owner_changes before update on public.groups for each row execute function public.protect_group_owner_changes();
