-- Sorasaki + Supabase
-- Cole este SQL no SQL Editor do seu projeto Supabase e execute.
-- As contas são gerenciadas pelo Supabase Auth. Nunca crie uma tabela própria para guardar senhas.

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null check (type in ('rating','suggestion')),
  rating integer check (rating is null or rating between 1 and 5),
  title text,
  message text,
  email text,
  status text not null default 'new' check (status in ('new','reviewing','planned','resolved','archived')),
  created_at timestamptz not null default now()
);

create table if not exists public.bug_reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  message text not null,
  page text,
  severity text not null default 'media' check (severity in ('baixa','media','alta','critica')),
  email text,
  status text not null default 'open' check (status in ('open','investigating','fixed','closed','duplicate')),
  created_at timestamptz not null default now()
);

create index if not exists idx_feedback_created_at on public.feedback(created_at desc);
create index if not exists idx_bug_created_at on public.bug_reports(created_at desc);

-- Limites de tamanho no banco (defesa em profundidade: o front-end já limita
-- com maxlength, mas qualquer pessoa pode chamar a API do Supabase direto
-- com a anon key e ignorar o HTML, então o limite real tem que estar aqui).
alter table public.feedback
  add constraint feedback_title_len check (title is null or char_length(title) <= 120),
  add constraint feedback_message_len check (message is null or char_length(message) <= 1800),
  add constraint feedback_email_len check (email is null or char_length(email) <= 160);

alter table public.bug_reports
  add constraint bug_title_len check (char_length(title) <= 120),
  add constraint bug_message_len check (char_length(message) <= 3000),
  add constraint bug_email_len check (email is null or char_length(email) <= 160);

alter table public.feedback enable row level security;
alter table public.bug_reports enable row level security;

drop policy if exists "users can insert own feedback" on public.feedback;
create policy "users can insert own feedback" on public.feedback
  for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "users can read own feedback" on public.feedback;
create policy "users can read own feedback" on public.feedback
  for select to authenticated using (auth.uid() = user_id);

drop policy if exists "users can insert own bug reports" on public.bug_reports;
create policy "users can insert own bug reports" on public.bug_reports
  for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "users can read own bug reports" on public.bug_reports;
create policy "users can read own bug reports" on public.bug_reports
  for select to authenticated using (auth.uid() = user_id);

-- Nenhuma policy de update/delete é criada de propósito: com RLS ligado e
-- sem policy, a operação é negada por padrão. Ninguém — nem o próprio autor
-- — pode editar ou apagar um feedback/bug já enviado pela API pública.

-- ===== Rate limit no banco (contra spam/flood mesmo de contas autenticadas) =====
-- Bloqueia um usuário que tente enviar mais de 5 registros em 10 minutos,
-- somando feedback + bug_reports. Isso protege o banco de ataques de
-- flood vindos de uma conta comprometida ou de um script automatizado,
-- e evita que a tabela cresça descontroladamente (o que degradaria o
-- painel de estatísticas e o próprio banco).
create or replace function public.enforce_rate_limit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  total integer;
begin
  select count(*) into total
  from (
    select created_at from public.feedback where user_id = new.user_id and created_at > now() - interval '10 minutes'
    union all
    select created_at from public.bug_reports where user_id = new.user_id and created_at > now() - interval '10 minutes'
  ) recentes;

  if total >= 5 then
    raise exception 'limite de envios atingido, tente novamente em alguns minutos';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_feedback_rate_limit on public.feedback;
create trigger trg_feedback_rate_limit
  before insert on public.feedback
  for each row execute function public.enforce_rate_limit();

drop trigger if exists trg_bug_rate_limit on public.bug_reports;
create trigger trg_bug_rate_limit
  before insert on public.bug_reports
  for each row execute function public.enforce_rate_limit();
