-- Sorasaki + Supabase
-- Cole este SQL no SQL Editor do seu projeto Supabase e execute.
-- As contas são gerenciadas pelo Supabase Auth. Nunca crie uma tabela própria para guardar senhas.

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null check (type in ('rating','suggestion')),
  rating integer check (rating is null or rating between 1 and 5),
  title text,
  message text,
  email text,
  status text not null default 'new' check (status in ('new','reviewing','planned','resolved','archived')),
  created_at timestamptz not null default now()
);

create table if not exists public.bug_reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  message text not null,
  page text,
  severity text not null default 'media' check (severity in ('baixa','media','alta','critica')),
  email text,
  status text not null default 'open' check (status in ('open','investigating','fixed','closed','duplicate')),
  created_at timestamptz not null default now()
);

create index if not exists idx_feedback_created_at on public.feedback(created_at desc);
create index if not exists idx_bug_created_at on public.bug_reports(created_at desc);

-- Limites de tamanho no banco (defesa em profundidade: o front-end já limita
-- com maxlength, mas qualquer pessoa pode chamar a API do Supabase direto
-- com a anon key e ignorar o HTML, então o limite real tem que estar aqui).
alter table public.feedback
  add constraint feedback_title_len check (title is null or char_length(title) <= 120),
  add constraint feedback_message_len check (message is null or char_length(message) <= 1800),
  add constraint feedback_email_len check (email is null or char_length(email) <= 160);

alter table public.bug_reports
  add constraint bug_title_len check (char_length(title) <= 120),
  add constraint bug_message_len check (char_length(message) <= 3000),
  add constraint bug_email_len check (email is null or char_length(email) <= 160);

alter table public.feedback enable row level security;
alter table public.bug_reports enable row level security;

drop policy if exists "users can insert own feedback" on public.feedback;
create policy "users can insert own feedback" on public.feedback
  for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "users can read own feedback" on public.feedback;
create policy "users can read own feedback" on public.feedback
  for select to authenticated using (auth.uid() = user_id);

drop policy if exists "users can insert own bug reports" on public.bug_reports;
create policy "users can insert own bug reports" on public.bug_reports
  for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "users can read own bug reports" on public.bug_reports;
create policy "users can read own bug reports" on public.bug_reports
  for select to authenticated using (auth.uid() = user_id);

-- Nenhuma policy de update/delete é criada de propósito: com RLS ligado e
-- sem policy, a operação é negada por padrão. Ninguém — nem o próprio autor
-- — pode editar ou apagar um feedback/bug já enviado pela API pública.

-- ===== Rate limit no banco (contra spam/flood mesmo de contas autenticadas) =====
-- Bloqueia um usuário que tente enviar mais de 5 registros em 10 minutos,
-- somando feedback + bug_reports. Isso protege o banco de ataques de
-- flood vindos de uma conta comprometida ou de um script automatizado,
-- e evita que a tabela cresça descontroladamente (o que degradaria o
-- painel de estatísticas e o próprio banco).
create or replace function public.enforce_rate_limit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  total integer;
begin
  select count(*) into total
  from (
    select created_at from public.feedback where user_id = new.user_id and created_at > now() - interval '10 minutes'
    union all
    select created_at from public.bug_reports where user_id = new.user_id and created_at > now() - interval '10 minutes'
  ) recentes;

  if total >= 5 then
    raise exception 'limite de envios atingido, tente novamente em alguns minutos';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_feedback_rate_limit on public.feedback;
create trigger trg_feedback_rate_limit
  before insert on public.feedback
  for each row execute function public.enforce_rate_limit();

drop trigger if exists trg_bug_rate_limit on public.bug_reports;
create trigger trg_bug_rate_limit
  before insert on public.bug_reports
  for each row execute function public.enforce_rate_limit();

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'user' check (role in ('user','admin')),
  display_name text,
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where user_id = auth.uid() and role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (user_id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1)))
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

insert into public.profiles (user_id, display_name)
select id, coalesce(raw_user_meta_data->>'display_name', split_part(email, '@', 1))
from auth.users
on conflict (user_id) do nothing;

create table if not exists public.groups (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  description text not null,
  category text not null check (category in ('vendas','comunidade','jogos','estudos','outros')),
  avatar_url text,
  member_count integer not null default 0 check (member_count >= 0),
  invite_url text not null,
  status text not null default 'pending' check (status in ('pending','approved','rejected','removed')),
  admin_note text,
  featured_by_admin boolean not null default false,
  admin_badge text check (admin_badge is null or admin_badge in ('oficial','indicado','parceiro')),
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (char_length(name) between 2 and 100),
  check (char_length(description) between 10 and 800),
  check (avatar_url is null or char_length(avatar_url) <= 1000),
  check (char_length(invite_url) between 10 and 1000),
  check (invite_url ~* '^https?://'),
  check (not featured_by_admin or status = 'approved')
);

create index if not exists idx_groups_status_created on public.groups(status, created_at desc);
create index if not exists idx_groups_owner on public.groups(owner_id, created_at desc);
create index if not exists idx_groups_category on public.groups(category, status);

create or replace function public.touch_group_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_groups_updated_at on public.groups;
create trigger trg_groups_updated_at
before update on public.groups
for each row execute function public.touch_group_updated_at();

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.groups(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  comment text check (comment is null or char_length(comment) <= 600),
  status text not null default 'visible' check (status in ('visible','hidden')),
  created_at timestamptz not null default now(),
  unique (group_id, user_id)
);

create index if not exists idx_reviews_group on public.reviews(group_id, status, created_at desc);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.groups(id) on delete cascade,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  reason text not null check (reason in ('spam','link_invalido','conteudo_inadequado','fraude','outro')),
  description text check (description is null or char_length(description) <= 800),
  status text not null default 'open' check (status in ('open','reviewing','resolved','dismissed')),
  created_at timestamptz not null default now()
);

create index if not exists idx_reports_status on public.reports(status, created_at desc);

create table if not exists public.promotion_plans (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text not null,
  price numeric(10,2) not null check (price >= 0),
  duration_days integer not null check (duration_days > 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  group_id bigint references public.groups(id) on delete set null,
  plan_id bigint references public.promotion_plans(id) on delete set null,
  amount numeric(10,2) not null check (amount >= 0),
  status text not null default 'pending' check (status in ('pending','paid','rejected','cancelled','expired','refunded')),
  payment_provider text not null default 'mercadopago',
  payment_id text,
  created_at timestamptz not null default now(),
  paid_at timestamptz,
  expires_at timestamptz
);

create index if not exists idx_orders_user on public.orders(user_id, created_at desc);
create index if not exists idx_orders_payment on public.orders(payment_provider, payment_id);

create table if not exists public.promotions (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.groups(id) on delete cascade,
  order_id bigint not null unique references public.orders(id) on delete cascade,
  plan_id bigint not null references public.promotion_plans(id) on delete restrict,
  starts_at timestamptz not null,
  expires_at timestamptz not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  check (expires_at > starts_at)
);

create index if not exists idx_promotions_active on public.promotions(active, expires_at desc);

alter table public.profiles enable row level security;
alter table public.groups enable row level security;
alter table public.reviews enable row level security;
alter table public.reports enable row level security;
alter table public.promotion_plans enable row level security;
alter table public.orders enable row level security;
alter table public.promotions enable row level security;

drop policy if exists "profiles own read" on public.profiles;
create policy "profiles own read" on public.profiles for select to authenticated using (auth.uid() = user_id or public.is_admin());

drop policy if exists "public approved groups read" on public.groups;
create policy "public approved groups read" on public.groups for select to anon, authenticated using (status = 'approved');

drop policy if exists "users own groups read" on public.groups;
create policy "users own groups read" on public.groups for select to authenticated using (auth.uid() = owner_id or public.is_admin());

drop policy if exists "users submit pending groups" on public.groups;
create policy "users submit pending groups" on public.groups for insert to authenticated with check (auth.uid() = owner_id and status = 'pending' and featured_by_admin = false and admin_badge is null);

drop policy if exists "admins manage groups" on public.groups;
create policy "admins manage groups" on public.groups for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "visible reviews read" on public.reviews;
create policy "visible reviews read" on public.reviews for select to anon, authenticated using (status = 'visible');

drop policy if exists "users create reviews" on public.reviews;
create policy "users create reviews" on public.reviews for insert to authenticated with check (auth.uid() = user_id and exists (select 1 from public.groups g where g.id = group_id and g.status = 'approved'));

drop policy if exists "users own reviews read" on public.reviews;
create policy "users own reviews read" on public.reviews for select to authenticated using (auth.uid() = user_id or public.is_admin());

drop policy if exists "admins manage reviews" on public.reviews;
create policy "admins manage reviews" on public.reviews for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "users create reports" on public.reports;
create policy "users create reports" on public.reports for insert to authenticated with check (auth.uid() = reporter_id);

drop policy if exists "users own reports read" on public.reports;
create policy "users own reports read" on public.reports for select to authenticated using (auth.uid() = reporter_id or public.is_admin());

drop policy if exists "admins manage reports" on public.reports;
create policy "admins manage reports" on public.reports for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "active plans read" on public.promotion_plans;
create policy "active plans read" on public.promotion_plans for select to anon, authenticated using (active = true or public.is_admin());

drop policy if exists "admins manage plans" on public.promotion_plans;
create policy "admins manage plans" on public.promotion_plans for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "users own orders read" on public.orders;
create policy "users own orders read" on public.orders for select to authenticated using (auth.uid() = user_id or public.is_admin());

drop policy if exists "admins manage orders" on public.orders;
create policy "admins manage orders" on public.orders for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "active promotions read" on public.promotions;
create policy "active promotions read" on public.promotions for select to anon, authenticated using (active = true or public.is_admin());

drop policy if exists "admins manage promotions" on public.promotions;
create policy "admins manage promotions" on public.promotions for all to authenticated using (public.is_admin()) with check (public.is_admin());

revoke all on public.profiles from anon;
revoke all on public.orders from anon;
revoke all on public.reports from anon;
revoke all on public.promotions from anon;
