-- Execute no SQL Editor do Supabase depois da migration/schema atual.
create table if not exists public.site_visits(visitor_id text not null,visit_day date not null default current_date,path text not null,page_views integer not null default 1 check(page_views>0),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),primary key(visitor_id,visit_day,path));
create index if not exists idx_site_visits_day on public.site_visits(visit_day desc);
create index if not exists idx_site_visits_path_day on public.site_visits(path,visit_day desc);
create or replace function public.record_site_visit(p_visitor_id text,p_path text) returns void language plpgsql security definer set search_path=public as $$ begin if p_visitor_id is null or p_visitor_id !~ '^[A-Za-z0-9_-]{20,120}$' then raise exception 'visitor inválido'; end if; if p_path is null or left(p_path,1) <> '/' or char_length(p_path)>180 then raise exception 'rota inválida'; end if; if p_path ~* '^/api(?:/|$)' or p_path ~* '^/controle-8f4c2e91(?:/|$)' then raise exception 'rota não rastreável'; end if; insert into public.site_visits(visitor_id,visit_day,path,page_views,updated_at) values(p_visitor_id,current_date,p_path,1,now()) on conflict(visitor_id,visit_day,path) do update set page_views=site_visits.page_views+1,updated_at=now(); end $$;
revoke all on function public.record_site_visit(text,text) from public;grant execute on function public.record_site_visit(text,text) to anon,authenticated;
alter table public.site_visits enable row level security;drop policy if exists "admins read site visits" on public.site_visits;create policy "admins read site visits" on public.site_visits for select to authenticated using(public.is_admin());revoke all on public.site_visits from anon,authenticated;grant select on public.site_visits to service_role;
update public.site_settings set value='false'::jsonb where key='maintenance_mode' and lower(trim(value #>> '{}')) in ('false','0','off','no');
create table if not exists public.products(id bigint generated by default as identity primary key,name text not null,slug text not null unique,description text,price numeric(10,2) not null default 0 check(price>=0),previous_price numeric(10,2),promo_price numeric(10,2),active boolean not null default true,display_order integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.products add column if not exists category text; alter table public.products add column if not exists image_url text; alter table public.products alter column promo_price drop not null; create index if not exists idx_products_active_order on public.products(active,display_order,created_at);alter table public.products enable row level security;drop policy if exists "public products read" on public.products;drop policy if exists "admins products" on public.products;create policy "public products read" on public.products for select to anon,authenticated using(active=true or public.is_admin());create policy "admins products" on public.products for all to authenticated using(public.is_admin()) with check(public.is_admin());

-- Agregador server-side: mantém o total histórico sem enviar identificadores de visitantes ao navegador.
create or replace function public.get_site_analytics()
returns jsonb language sql security definer set search_path=public as $$
with daily as (
  select visit_day, count(distinct visitor_id)::integer as visitors, sum(page_views)::bigint as page_views
  from public.site_visits
  where visit_day >= current_date - 29
  group by visit_day
), pages as (
  select path, sum(page_views)::bigint as page_views
  from public.site_visits group by path order by page_views desc limit 10
), days as (
  select generate_series(current_date - 29, current_date, interval '1 day')::date as day
)
select jsonb_build_object(
  'ok',true,
  'website',jsonb_build_object(
    'unique_visitors_total',(select count(distinct visitor_id)::bigint from public.site_visits),
    'unique_visitors_today',(select count(distinct visitor_id)::bigint from public.site_visits where visit_day=current_date),
    'page_views_total',(select coalesce(sum(page_views),0)::bigint from public.site_visits),
    'page_views_today',(select coalesce(sum(page_views),0)::bigint from public.site_visits where visit_day=current_date),
    'daily',coalesce((select jsonb_agg(jsonb_build_object('day',days.day,'visitors',coalesce(daily.visitors,0),'page_views',coalesce(daily.page_views,0)) order by days.day) from days left join daily on daily.visit_day=days.day),'[]'::jsonb),
    'top_pages',coalesce((select jsonb_agg(jsonb_build_object('path',pages.path,'page_views',pages.page_views) order by pages.page_views desc) from pages),'[]'::jsonb)
  )
);
$$;
revoke all on function public.get_site_analytics() from public;
grant execute on function public.get_site_analytics() to anon, authenticated;

-- A imagem de manutenção é parte do projeto; a aplicação usa /sorasaki-manutencao.jpg.
update public.site_settings set value='false'::jsonb where key='maintenance_mode' and value::text in ('"false"','false');
